export const CSV_CATEGORIES = [
  { n1: "Fijos", n2: "Servicios Domiciliarios", n3: "Energía Eléctrica", n4: "Edelap" },
  { n1: "Fijos", n2: "Servicios Domiciliarios", n3: "Comunicaciones", n4: "Internet (Starlink)" },
  { n1: "Fijos", n2: "Servicios Domiciliarios", n3: "Administración", n4: "Expensas (Terreno)" },
  { n1: "Fijos", n2: "Servicios Domiciliarios", n3: "Administración", n4: "Impuestos" },
  { n1: "Fijos", n2: "Servicios Domiciliarios", n3: "Energía Eléctrica", n4: "Otras compañías" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Carne picada" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Vacío" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Asado" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Bife" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Hamburguesas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Achuras" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Vaca - Morcilla" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Carnes Rojas", n4: "Otros cortes vaca" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Cerdo - Pechito" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Cerdo - Bondiola" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Cerdo - Costeleta" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Cerdo - Chorizos" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Cerdo - Hamburguesas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Cerdo", n4: "Otros cortes cerdo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Aves", n4: "Pollo - Alitas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Aves", n4: "Pollo - Pata y muslo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Aves", n4: "Pollo - Pechuga" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Aves", n4: "Pollo - Completo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Aves", n4: "Otras aves" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Proteínas Animales - Otros", n4: "Otras carnes" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Salame" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Bondiola" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Crudo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Mortadela" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Paleta" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Queso" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Fiambrería y Embutidos", n4: "Otros fiambres" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Pera" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Banana" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Naranja" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Pomelo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Ciruela" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Frutilla" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Durazno" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Melón" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Tomate" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Limón" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Frutas", n4: "Otras frutas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Rúcula" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Zanahoria" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Batata" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Papa" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Cebolla" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Morrón" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Hinojo" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Brócoli" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Verduras", n4: "Otras verduras" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Arvejas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Atún" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Aceitunas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Caballa" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Jurel" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Puré de tomates" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Sardina" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Conservas", n4: "Otras conservas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Otros", n4: "Preservativos" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Bebidas", n4: "Vino" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Almacén - Otros", n4: "Otros productos almacén" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Yerba" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Aceite de oliva" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Aceite de coco" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Tés e Infusiones" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Sal" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Bicarbonato" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Frutos secos" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Harinas" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Productos Dietéticos", n4: "Chocolate" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Suplementos", n4: "Creatina" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Suplementos", n4: "Colágeno" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Suplementos", n4: "Magnesio" },
  { n1: "Variables", n2: "Alimentación Básica", n3: "Suplementos", n4: "Otros suplementos" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Papel higiénico" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Jabón líquido" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Jabón tocador" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Jabón lavarropa" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Rollo cocina" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Jabón" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Detergente" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Alcohol" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Quita manchas" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Shampoo" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Acondicionador" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Higiene femenina" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Higiene Personal", n4: "Pasta dental" },
  { n1: "Variables", n2: "Higiene y Limpieza", n3: "Limpieza del Hogar", n4: "Otros limpieza" },
  { n1: "Variables", n2: "Permisibles y Ocasionales", n3: "Golosinas y Dulces", n4: "Chocolate" },
  { n1: "Variables", n2: "Permisibles y Ocasionales", n3: "Helados", n4: "Helado" },
  { n1: "Variables", n2: "Permisibles y Ocasionales", n3: "Panificados Especiales", n4: "Chipá" },
  { n1: "Variables", n2: "Permisibles y Ocasionales", n3: "Snacks y Picadas", n4: "Papas fritas" },
  { n1: "Variables", n2: "Permisibles y Ocasionales", n3: "Panificados Especiales", n4: "Panederil" },
  { n1: "Extraordinarios", n2: "Mejoras y Mantenimiento", n3: "Reparaciones y Construcción", n4: "Materiales ferretería" },
  { n1: "Extraordinarios", n2: "Mejoras y Mantenimiento", n3: "Electricidad e Instalaciones", n4: "Materiales eléctricos" },
  { n1: "Extraordinarios", n2: "Mejoras y Mantenimiento", n3: "Otras Mejoras", n4: "Otras mejoras hogar" },
  { n1: "Extraordinarios", n2: "Energía y Combustibles", n3: "Combustibles Gaseosos", n4: "Gas (Garrafa)" },
  { n1: "Extraordinarios", n2: "Energía y Combustibles", n3: "Combustibles Sólidos", n4: "Leña" },
  { n1: "Extraordinarios", n2: "Energía y Combustibles", n3: "Combustibles Líquidos", n4: "Nafta" },
  { n1: "Extraordinarios", n2: "Energía y Combustibles", n3: "Combustibles Sólidos", n4: "Carbón" },
  { n1: "Extraordinarios", n2: "Otros Extraordinarios", n3: "Varios", n4: "Otras categorías extraordinarias" },
  { n1: "Imprevistos", n2: "Emergencias", n3: "Varios", n4: "Otros imprevistos" },
]

export const UNITS = ["unidad","kg","gr","litro","ml","paquete","caja","docena","metro","garrafa","bolsa","porción","rollo"]

export const N1_COLORS = {
  "Fijos":           { bg: "#1e40af", light: "#dbeafe", text: "#1e40af" },
  "Variables":       { bg: "#059669", light: "#d1fae5", text: "#059669" },
  "Extraordinarios": { bg: "#d97706", light: "#fef3c7", text: "#d97706" },
  "Imprevistos":     { bg: "#dc2626", light: "#fee2e2", text: "#dc2626" },
}

export const CHART_COLORS = ["#3b82f6","#10b981","#f59e0b","#ef4444","#8b5cf6","#ec4899","#06b6d4","#f97316","#84cc16","#a78bfa"]

export const fmt = (n) =>
  new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 }).format(n || 0)

export const fmtDate = (d) =>
  d ? new Date(d + "T00:00:00").toLocaleDateString("es-AR") : "-"

export function uniq(arr) { return [...new Set(arr)] }
